/**
 * HeightmapImporter.js
 *
 * Two-phase heightmap import:
 *
 *   Phase 1 — Analysis (analyzeImage)
 *     Loads the image, reads pixel data via OffscreenCanvas, and auto-detects
 *     how many discrete elevation bands the image uses.
 *
 *   Phase 2 — Options dialog (showImportOptionsDialog)
 *     Presents a DialogV2.confirm() so the GM can set base elevation,
 *     increment, band count (pre-filled from auto-detection), encoding mode,
 *     and brightness inversion.  Returns the chosen options, or null if
 *     the dialog is cancelled.
 *
 *   Phase 3 — Sampling (sampleToHeightmap)
 *     Called by ContourLayer.applyImportPreview() after the GM has positioned
 *     and sized the image preview on the canvas.  Maps each heightmap cell to
 *     an image pixel using the sprite's current scene-space rect, converts
 *     brightness to an elevation value, and writes it into the heightmap.
 *     Cells whose scene-space centre falls outside the sprite are left unchanged.
 *
 * Encoding notes
 * ──────────────
 *   8-bit (default)
 *     Any PNG/JPEG/WebP.  The red channel (0–255) is used as brightness.
 *
 *   16-bit via R+G channels
 *     A PNG where high byte is in R and low byte in G:
 *       value = R * 256 + G   (range 0 – 65535)
 *     This is a common GIS and Foundry-exporter convention for 16-bit height
 *     maps stored inside an 8-bit-per-channel PNG.
 */

// ── Internal helpers ──────────────────────────────────────────────────────────

/**
 * Load a URL into an HTMLImageElement.
 * @param {string} url
 * @returns {Promise<HTMLImageElement>}
 */
function loadImage(url) {
  return new Promise((resolve, reject) => {
    const img = new Image();
    img.onload  = () => resolve(img);
    img.onerror = () => reject(new Error("Failed to load image — unsupported format or corrupt file."));
    img.src = url;
  });
}

/**
 * Auto-detect the number of discrete elevation bands in an image.
 *
 * Strategy: quantise each pixel's brightness (R channel) into 5 % steps
 * (20 buckets, 0–20) and count distinct occupied buckets.  Subtract one
 * for bucket 0 (the "base / black" level) if it is present.
 *
 * This works well for heightmaps generated by discrete painting tools
 * (including this module) and gives a reasonable estimate for external
 * topographic images.  The GM can always override the suggested value.
 *
 * @param {Uint8ClampedArray} pixels  RGBA pixel data
 * @param {number}            total   Total pixel count (imgW × imgH)
 * @returns {number}  Estimated band count (1–100)
 */
function detectBandCount(pixels, total) {
  const buckets = new Set();
  for (let i = 0; i < total; i++) {
    // Round brightness to nearest 5 % step (0 … 20)
    const bucket = Math.round((pixels[i * 4] / 255) * 20);
    buckets.add(bucket);
  }
  const hasBase  = buckets.has(0);
  const count    = hasBase ? buckets.size - 1 : buckets.size;
  return Math.max(1, Math.min(100, count));
}

// ── Public API ────────────────────────────────────────────────────────────────

/**
 * Load an image file and return its pixel data + auto-detected band count.
 *
 * The blob URL is created and revoked internally; the caller receives the
 * decoded HTMLImageElement (kept alive for PIXI.Texture creation later) and
 * a Uint8ClampedArray of RGBA pixels.
 *
 * @param {File} file
 * @returns {Promise<{imageEl:HTMLImageElement, pixels:Uint8ClampedArray, imgW:number, imgH:number, detectedBands:number}>}
 */
export async function analyzeImage(file) {
  const url = URL.createObjectURL(file);
  let imageEl;
  try {
    imageEl = await loadImage(url);
  } finally {
    // Revoke the blob URL.  The imageEl keeps its decoded bitmap in memory
    // even after the URL is revoked, so PIXI.Texture.from(imageEl) still works.
    URL.revokeObjectURL(url);
  }

  const oc  = new OffscreenCanvas(imageEl.naturalWidth, imageEl.naturalHeight);
  const ctx = oc.getContext("2d");
  ctx.drawImage(imageEl, 0, 0);
  const imageData = ctx.getImageData(0, 0, imageEl.naturalWidth, imageEl.naturalHeight);

  const imgW   = imageEl.naturalWidth;
  const imgH   = imageEl.naturalHeight;
  const pixels = imageData.data;
  const detectedBands = detectBandCount(pixels, imgW * imgH);

  return { imageEl, pixels, imgW, imgH, detectedBands };
}

/**
 * Show a DialogV2.confirm() with import options.
 *
 * The "yes" button callback reads the form values before the dialog closes,
 * so the caller receives a fully populated options object.  Returns null
 * if the GM cancels or closes the dialog.
 *
 * @param {{ detectedBands:number }}  analysis        From analyzeImage()
 * @param {{ baseElevation:number, increment:number }} currentSettings  Layer settings
 * @returns {Promise<{baseElevation:number, increment:number, numBands:number,
 *                    mode:string, invert:boolean}|null>}
 */
export async function showImportOptionsDialog(analysis, currentSettings) {
  const { detectedBands }                         = analysis;
  const { baseElevation = 0, increment = 5 }      = currentSettings;

  let opts = null;

  await foundry.applications.api.DialogV2.confirm({
    window:  { title: "Import Heightmap — Options" },
    content: `
      <p>
        Configure how the image maps to elevation values, then click
        <strong>Preview on Scene</strong> to position it before committing.
      </p>

      <div class="form-group">
        <label>Base Elevation <span class="units">(ft)</span></label>
        <div class="form-fields">
          <input type="number" id="cr-imp-base"
                 value="${baseElevation}" min="0" step="1" style="width:6em">
        </div>
        <p class="hint">Elevation of the darkest (black) pixels.</p>
      </div>

      <div class="form-group">
        <label>Increment <span class="units">(ft per band)</span></label>
        <div class="form-fields">
          <input type="number" id="cr-imp-inc"
                 value="${increment}" min="1" max="1000" step="1" style="width:6em">
        </div>
        <p class="hint">Elevation step between consecutive bands.</p>
      </div>

      <div class="form-group">
        <label>Number of Bands</label>
        <div class="form-fields">
          <input type="number" id="cr-imp-bands"
                 value="${detectedBands}" min="1" max="100" step="1" style="width:6em">
        </div>
        <p class="hint">
          Auto-detected: <strong>${detectedBands}</strong> distinct
          tone${detectedBands === 1 ? "" : "s"} found in this image.
          Adjust if needed.
        </p>
      </div>

      <div class="form-group">
        <label>Pixel encoding</label>
        <div class="form-fields">
          <select id="cr-imp-mode">
            <option value="8bit" selected>8-bit greyscale (standard PNG/JPEG)</option>
            <option value="16bit">16-bit via R+G channels (GIS / Foundry export)</option>
          </select>
        </div>
        <p class="hint">
          Use <em>16-bit via R+G</em> only for images exported by tools that
          encode 16-bit heights as R×256+G (e.g. Foundry's own height exporter).
        </p>
      </div>

      <div class="form-group">
        <label>Invert brightness</label>
        <div class="form-fields">
          <input type="checkbox" id="cr-imp-invert">
        </div>
        <p class="hint">Check if <em>black = high elevation</em>, white = low.</p>
      </div>
    `,
    yes: {
      label:    "Preview on Scene",
      icon:     "fa-solid fa-eye",
      callback: (event, button, dialog) => {
        // In FoundryVTT v13 the callback receives the ApplicationV2 instance,
        // not the HTMLElement.  Use dialog.element to reach the rendered DOM.
        const root  = dialog.element ?? dialog;
        const base  = parseInt(root.querySelector("#cr-imp-base")?.value  ?? String(baseElevation), 10);
        const inc   = parseInt(root.querySelector("#cr-imp-inc")?.value   ?? String(increment),     10);
        const bands = parseInt(root.querySelector("#cr-imp-bands")?.value ?? String(detectedBands), 10);
        opts = {
          baseElevation: isNaN(base)  ? baseElevation : Math.max(0, base),
          increment:     isNaN(inc)   ? increment     : Math.max(1, inc),
          numBands:      isNaN(bands) ? detectedBands : Math.max(1, Math.min(100, bands)),
          mode:          root.querySelector("#cr-imp-mode")?.value ?? "8bit",
          invert:        root.querySelector("#cr-imp-invert")?.checked ?? false,
        };
      },
    },
    no: {
      label: "Cancel",
      icon:  "fa-solid fa-xmark",
    },
    rejectClose: false,
  });

  return opts;
}

/**
 * Sample pixel data from an image into a HeightmapData.
 *
 * Only heightmap cells whose scene-space centre falls inside the sprite
 * footprint are modified.  Cells outside are left unchanged, so a small
 * import image can be placed on just one part of the scene.
 *
 * @param {Uint8ClampedArray} pixels     RGBA pixel data from analyzeImage()
 * @param {number}            imgW       Image width in pixels
 * @param {number}            imgH       Image height in pixels
 * @param {{x:number,y:number,width:number,height:number,rotation?:number}} spriteRect
 *   Current position/size/rotation of the preview sprite in scene coordinates.
 *   x/y are the world-space CENTRE (center-pivot); rotation is in radians (default 0).
 * @param {HeightmapData} heightmap      Destination heightmap (mutated in-place)
 * @param {object}        options        { baseElevation, increment, numBands, mode, invert }
 */
export function sampleToHeightmap(pixels, imgW, imgH, spriteRect, heightmap, options) {
  const { baseElevation, increment, numBands, mode = "8bit", invert = false } = options;
  const { cellSize, cols, rows } = heightmap;
  const sceneOffsetX = canvas.dimensions.sceneRect.x;
  const sceneOffsetY = canvas.dimensions.sceneRect.y;

  const { x: centerX, y: centerY, width: sw, height: sh, rotation = 0 } = spriteRect;
  const cosT  = Math.cos(-rotation);
  const sinT  = Math.sin(-rotation);
  const hw = sw / 2, hh = sh / 2;

  for (let cy = 0; cy < rows; cy++) {
    for (let cx = 0; cx < cols; cx++) {
      // Scene-space centre of this cell
      const sceneX = sceneOffsetX + cx * cellSize + cellSize * 0.5;
      const sceneY = sceneOffsetY + cy * cellSize + cellSize * 0.5;

      // Translate to sprite-centre-relative coordinates and un-rotate
      const dx = sceneX - centerX, dy = sceneY - centerY;
      const lx = dx * cosT - dy * sinT; // local X in sprite space
      const ly = dx * sinT + dy * cosT; // local Y in sprite space

      // Skip cells outside the sprite footprint
      if (lx < -hw || lx > hw || ly < -hh || ly > hh) continue;

      // Normalised position within the sprite (0 … 1)
      const normX = (lx + hw) / sw;
      const normY = (ly + hh) / sh;

      // Nearest-neighbour sample
      const imgX = Math.min(imgW - 1, Math.floor(normX * imgW));
      const imgY = Math.min(imgH - 1, Math.floor(normY * imgH));
      const pIdx = (imgY * imgW + imgX) * 4;

      let brightness;
      if (mode === "16bit") {
        brightness = (pixels[pIdx] * 256 + pixels[pIdx + 1]) / 65535;
      } else {
        brightness = pixels[pIdx] / 255;
      }
      if (invert) brightness = 1 - brightness;

      const band = Math.round(brightness * numBands);
      const elev = baseElevation + band * increment; // black (band 0) → baseElevation
      heightmap.set(cx, cy, Math.max(0, Math.min(65535, elev)));
    }
  }
}
